project_name: dockertags
builds:
  - main: cmd/dockertags/main.go
    binary: dockertags
    ldflags:
      - -s -w
      - "-extldflags '-static'"
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7

nfpms:
  -
    formats:
      - apk
      - deb
      - rpm
    vendor: "goodwithtech"
    homepage: "https://github.com/goodwithtech"
    maintainer: "Tomoya Amachi <tomoya.amachi@gmail.com>"
    description: "a CLI tool for fetching container image tags"
    license: "AGPL"
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD

archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
    files:
      - README.md
      - LICENSE

brews:
  -
    tap:
      owner: goodwithtech
      name: homebrew-r
    folder: Formula
    homepage: "https://github.com/goodwithtech/dockertags"
    description: "a CLI tool for fetching container image tags."
    test: |
      system "#{bin}/dockertags --version"

dockers:
  - image_templates:
      - 'goodwithtech/dockertags:{{ .Tag }}-amd64'
      - 'ghcr.io/goodwithtech/dockertags:{{ .Tag }}-amd64'
    dockerfile: Dockerfile.releaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    extra_files:
      - assets/cert.crt
  - image_templates:
      - 'goodwithtech/dockertags:{{ .Tag }}-arm64'
      - 'ghcr.io/goodwithtech/dockertags:{{ .Tag }}-arm64'
    dockerfile: Dockerfile.releaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - assets/cert.crt
docker_manifests:
  - name_template: 'goodwithtech/dockertags:{{ .Tag }}'
    image_templates:
      - 'goodwithtech/dockertags:{{ .Tag }}-amd64'
      - 'goodwithtech/dockertags:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/goodwithtech/dockertags:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/goodwithtech/dockertags:{{ .Tag }}-amd64'
      - 'ghcr.io/goodwithtech/dockertags:{{ .Tag }}-arm64'
  - name_template: 'goodwithtech/dockertags:latest'
    image_templates:
      - 'goodwithtech/dockertags:{{ .Tag }}-amd64'
      - 'goodwithtech/dockertags:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/goodwithtech/dockertags:latest'
    image_templates:
      - 'ghcr.io/goodwithtech/dockertags:{{ .Tag }}-amd64'
      - 'ghcr.io/goodwithtech/dockertags:{{ .Tag }}-arm64'