project_name: dockertags
builds:
  - main: cmd/dockertags/main.go
    binary: dockertags
    ldflags:
      - -s -w
      - "-extldflags '-static'"
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
#      - darwin
      - linux
#      - windows
#      - freebsd
#      - openbsd
#    goarch:
#      - amd64
#      - 386
#      - arm
#      - arm64
#    goarm:
#      - 7
#
#nfpms:
#  -
#    id: dockertags
#    formats:
#      - deb
#      - rpm
#    vendor: "goodwithtech"
#    homepage: "https://github.com/goodwithtech"
#    maintainer: "Tomoya Amachi <tomoya.amachi@gmail.com>"
#    description: "docker container tag viewer"
#    license: "AGPL"
#    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
#    replacements:
#      amd64: 64bit
#      386: 32bit
#      arm: ARM
#      arm64: ARM64
#      darwin: Darwin
#      linux: Linux
#      windows: Windows
#      openbsd: OpenBSD
#      netbsd: NetBSD
#      freebsd: FreeBSD
#      dragonfly: DragonFlyBSD
#
#archives:
#  -
#    id: dockertags
#    format: tar.gz
#    format_overrides:
#      - goos: windows
#        format: zip
#    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
#    replacements:
#      amd64: 64bit
#      386: 32bit
#      arm: ARM
#      arm64: ARM64
#      darwin: macOS
#      linux: Linux
#      windows: Windows
#      openbsd: OpenBSD
#      netbsd: NetBSD
#      freebsd: FreeBSD
#      dragonfly: DragonFlyBSD
#    files:
#      - README.md
#      - LICENSE
#
#brews:
#  -
#    github:
#      owner: goodwithtech
#      name: homebrew-r
#    folder: Formula
#    homepage: "https://github.com/goodwithtech/dockertags"
#    description: "docker container tag viewer"
#    test: |
#      system "#{bin}/program --version"

dockers:
  -
    image_templates:
      - "docker.io/goodwithtech/dockertags:{{ .Tag }}"
      - "docker.io/goodwithtech/dockertags:latest"
    binaries:
      - dockertags
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.description=Fetching and summarizing remote docker image tags"
      - "--label=org.label-schema.vendor=Goodwith"
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.build-date={{ .Date }}"
      - "--label=org.label-schema.vcs=https://github.com/goodwithtech/dockertags"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"