defaults: &defaults
  working_directory: /go/src/github.com/goodwithtech/dockertags
  docker:
    - image: circleci/golang:1.13
      environment:
        GO111MODULE: "on"
  steps:
    - restore_cache:
      name: Restore go modules cache
      keys:
        - go-mod-v1-{{ checksum "go.sum" }}
    - save_cache:
      key: go-mod-v1-{{ checksum "go.sum" }}
      paths:
        - "/go/pkg/mod"

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: go test ./...
  release:
    <<: *defaults
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: setup docker
          command: docker login -u goodwithtech -p $DOCKERHUB_TOKEN
      - run:
          name: release
          command: sudo apt-get install -y rpm && curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - test